Repository moraguma/GamutoWare, pull requests merged in 2023-04, with the labels that each got.

#45 Reimplements IFUV
  .godot/editor/editor_layout.cfg
  .godot/editor/filesystem_update4
  .godot/editor/project_metadata.cfg
  .godot/editor/script_editor_cache.cfg
  .godot/uid_cache.bin
  Godot4TODO.txt
  microjogos/moraguma/ifuv/cenas/Main.tscn
  microjogos/moraguma/ifuv/cenas/NumberButton.tscn
  microjogos/moraguma/ifuv/cenas/scripts/Main.gd
  microjogos/moraguma/ifuv/cenas/scripts/NumberButton.gd
  principal/creditos.txt
  principal/recursos/data/Minigames.gd
  principal/saves/save.tres
Labels: Complete Minigame

#46 Adds save.tres to gitignore
  .gitignore
Labels: Enhancement

#48 Create README.md
  README.md
Labels: Enhancement

#49 Adds Packs-projeto-enzo-bertoloti
  microjogos/2023S1/projeto-enzo-bertoloti/capa.png
  microjogos/2023S1/projeto-enzo-bertoloti/capa.png.import
  microjogos/2023S1/projeto-enzo-bertoloti/cenas/cenas.txt
  microjogos/2023S1/projeto-enzo-bertoloti/cenas/main.tscn
  microjogos/2023S1/projeto-enzo-bertoloti/cenas/mapa1.tscn
  microjogos/2023S1/projeto-enzo-bertoloti/cenas/mapa2.tscn
  microjogos/2023S1/projeto-enzo-bertoloti/cenas/mapa3.tscn
  microjogos/2023S1/projeto-enzo-bertoloti/cenas/mapa4.tscn
  microjogos/2023S1/projeto-enzo-bertoloti/cenas/scripts/Camera2D.gd
  microjogos/2023S1/projeto-enzo-bertoloti/cenas/scripts/CharacterBody2D.gd
  microjogos/2023S1/projeto-enzo-bertoloti/cenas/scripts/main.gd
  microjogos/2023S1/projeto-enzo-bertoloti/cenas/scripts/scripts.txt
  microjogos/2023S1/projeto-enzo-bertoloti/cenas/tileset.tres
  microjogos/2023S1/projeto-enzo-bertoloti/creditos.gd
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/MIOJO_DO_MAL.png.import
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/MIOJO_DO_MAL_pb.png
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/MIOJO_DO_MAL_pb.png.import
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/Sons/Jesús Lastra - Slow Down.mp3
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/Sons/Jesús Lastra - Slow Down.mp3.import
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/Sons/SFX_Explosion_01.wav
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/Sons/SFX_Explosion_01.wav.import
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/Sons/pulo.wav
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/Sons/pulo.wav.import
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/Tilemap/monochrome_tilemap.png
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/Tilemap/monochrome_tilemap.png.import
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/Tilemap/monochrome_tilemap_packed.png
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/Tilemap/monochrome_tilemap_packed.png.import
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/Tilemap/monochrome_tilemap_packed_scaled_6x_pngcrushed.png
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/Tilemap/monochrome_tilemap_packed_scaled_6x_pngcrushed.png.import
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/Tilemap/monochrome_tilemap_transparent.png
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/Tilemap/monochrome_tilemap_transparent.png.import
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/Tilemap/monochrome_tilemap_transparent_packed.png
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/Tilemap/monochrome_tilemap_transparent_packed.png.import
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/Tilemap/monochrome_tilemap_transparent_packed_scaled_6x_pngcrushed.png
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/Tilemap/monochrome_tilemap_transparent_packed_scaled_6x_pngcrushed.png.import
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/placeholder.png.import
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/player.png
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/player.png.import
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/recursos.txt
  microjogos/2023S1/projeto-enzo-bertoloti/recursos/tileset.webp.import
  microjogos/2023S1/projeto-enzo-bertoloti/seu projeto.txt
  principal/recursos/data/Minigames.gd
Labels: Minigame Implementation

#50 Removes unneeded files
  microjogos/2023S1/projeto-tiagoperrupato/capa.png
  microjogos/2023S1/projeto-tiagoperrupato/capa.png.import
  microjogos/2023S1/projeto-tiagoperrupato/cenas/cenas.txt
  microjogos/2023S1/projeto-tiagoperrupato/cenas/main.tscn
  microjogos/2023S1/projeto-tiagoperrupato/cenas/scripts/Jogador.gd
  microjogos/2023S1/projeto-tiagoperrupato/cenas/scripts/Veiculos.gd
  microjogos/2023S1/projeto-tiagoperrupato/cenas/scripts/main.gd
  microjogos/2023S1/projeto-tiagoperrupato/cenas/scripts/musica-trafico.gd
  microjogos/2023S1/projeto-tiagoperrupato/cenas/scripts/scripts.txt
  microjogos/2023S1/projeto-tiagoperrupato/creditos.gd
  microjogos/2023S1/projeto-tiagoperrupato/recursos/Porsche 911 Carrera 1998.png
  microjogos/2023S1/projeto-tiagoperrupato/recursos/Porsche 911 Carrera 1998.png.import
  microjogos/2023S1/projeto-tiagoperrupato/recursos/car-truck2.png
  microjogos/2023S1/projeto-tiagoperrupato/recursos/car-truck2.png.import
  microjogos/2023S1/projeto-tiagoperrupato/recursos/car-truck3.png
  microjogos/2023S1/projeto-tiagoperrupato/recursos/car-truck3.png.import
  microjogos/2023S1/projeto-tiagoperrupato/recursos/car-truck4.png
  microjogos/2023S1/projeto-tiagoperrupato/recursos/car-truck4.png.import
  microjogos/2023S1/projeto-tiagoperrupato/recursos/car-truck5.png
  microjogos/2023S1/projeto-tiagoperrupato/recursos/car-truck5.png.import
  microjogos/2023S1/projeto-tiagoperrupato/recursos/carro2.png
  microjogos/2023S1/projeto-tiagoperrupato/recursos/carro2.png.import
  microjogos/2023S1/projeto-tiagoperrupato/recursos/carro3.png
  microjogos/2023S1/projeto-tiagoperrupato/recursos/carro3.png.import
  microjogos/2023S1/projeto-tiagoperrupato/recursos/explosion.png
  microjogos/2023S1/projeto-tiagoperrupato/recursos/explosion.png.import
  microjogos/2023S1/projeto-tiagoperrupato/recursos/explosion.wav
  microjogos/2023S1/projeto-tiagoperrupato/recursos/explosion.wav.import
  microjogos/2023S1/projeto-tiagoperrupato/recursos/gatve Varniu.ogg
  microjogos/2023S1/projeto-tiagoperrupato/recursos/gatve Varniu.ogg.import
  microjogos/2023S1/projeto-tiagoperrupato/recursos/moto1.png
  microjogos/2023S1/projeto-tiagoperrupato/recursos/moto1.png.import
  microjogos/2023S1/projeto-tiagoperrupato/recursos/recursos.txt
  microjogos/2023S1/projeto-tiagoperrupato/recursos/rua.png
  microjogos/2023S1/projeto-tiagoperrupato/recursos/rua.png.import
  microjogos/2023S1/projeto-tiagoperrupato/seu projeto.txt
  principal/recursos/data/Minigames.gd
Labels: Minigame Implementation

#52 Fixes sound Tiago Perrupato
  microjogos/2023S1/projeto-tiagoperrupato/cenas/main.tscn
  microjogos/2023S1/projeto-tiagoperrupato/cenas/scripts/musica-trafico.gd
Labels: Bug

#55 Returns seu_projeto to original state
  microjogos/2023S1/seu_projeto/cenas/main.tscn
Labels: Bug

#56 Reimplements Whale Eater
  microjogos/2022S1/gamuturai/cenas/main.tscn
Labels: Minigame Implementation

#57 ACTUALLY reimplements Whale Eater
  microjogos/moraguma/whale_eater/cenas/Main.tscn
  microjogos/moraguma/whale_eater/cenas/Player.tscn
  microjogos/moraguma/whale_eater/cenas/scripts/Main.gd
  microjogos/moraguma/whale_eater/cenas/scripts/Player.gd
  microjogos/moraguma/whale_eater/recursos/tilesets/whaleeater.tres
  principal/recursos/data/Minigames.gd
Labels: Minigame Implementation

#34 Glassmuto
  microjogos/2023S1/GamutoVeiga/capa.png
  microjogos/2023S1/GamutoVeiga/capa.png.import
  microjogos/2023S1/GamutoVeiga/cenas/cenas.txt
  microjogos/2023S1/GamutoVeiga/cenas/main.tscn
  microjogos/2023S1/GamutoVeiga/cenas/node_2d.tscn
  microjogos/2023S1/GamutoVeiga/cenas/scripts/Copo 1.gd
  microjogos/2023S1/GamutoVeiga/cenas/scripts/Copo 2.gd
  microjogos/2023S1/GamutoVeiga/cenas/scripts/Copo 3.gd
  microjogos/2023S1/GamutoVeiga/cenas/scripts/Copo2.gd
  microjogos/2023S1/GamutoVeiga/cenas/scripts/main.gd
  microjogos/2023S1/GamutoVeiga/cenas/scripts/node_2d.gd
  microjogos/2023S1/GamutoVeiga/cenas/scripts/scripts.txt
  microjogos/2023S1/GamutoVeiga/creditos.gd
  microjogos/2023S1/GamutoVeiga/recursos/3045034132_1.webp.import
  microjogos/2023S1/GamutoVeiga/recursos/94c9ea25ba53d22187b83be2e6cad233.webp.import
  microjogos/2023S1/GamutoVeiga/recursos/CRmABX.png.import
  microjogos/2023S1/GamutoVeiga/recursos/Copo.png
  microjogos/2023S1/GamutoVeiga/recursos/Copo.png.import
  microjogos/2023S1/GamutoVeiga/recursos/Fundo.png
  microjogos/2023S1/GamutoVeiga/recursos/Fundo.png.import
  microjogos/2023S1/GamutoVeiga/recursos/Glassmuto_song.ogg
  microjogos/2023S1/GamutoVeiga/recursos/Glassmuto_song.ogg.import
  microjogos/2023S1/GamutoVeiga/recursos/gamuto.png
  microjogos/2023S1/GamutoVeiga/recursos/gamuto.png.import
  microjogos/2023S1/GamutoVeiga/recursos/recursos.txt
  microjogos/2023S1/GamutoVeiga/recursos/seta.png
  microjogos/2023S1/GamutoVeiga/recursos/seta.png.import
  microjogos/2023S1/GamutoVeiga/seu projeto.txt
Labels: Complete minigame, Missing sound
