Repository moraguma/GamutoWare, pull requests merged in 2023-08, with the labels that each got.

#5 Criar pasta do microjogo
  microjogos/2023S1/projetoAnaBeatriz/capa.png
  microjogos/2023S1/projetoAnaBeatriz/capa.png.import
  microjogos/2023S1/projetoAnaBeatriz/cenas/Area2D.gd
  microjogos/2023S1/projetoAnaBeatriz/cenas/Area2D3.gd
  microjogos/2023S1/projetoAnaBeatriz/cenas/CharacterBody2D.gd
  microjogos/2023S1/projetoAnaBeatriz/cenas/CollisionShape2D.gd
  microjogos/2023S1/projetoAnaBeatriz/cenas/CollisionShape2D2.gd
  microjogos/2023S1/projetoAnaBeatriz/cenas/Inimigo.tscn
  microjogos/2023S1/projetoAnaBeatriz/cenas/Inimigos2.gd
  microjogos/2023S1/projetoAnaBeatriz/cenas/Inimki.gd
  microjogos/2023S1/projetoAnaBeatriz/cenas/Nave1.gd
  microjogos/2023S1/projetoAnaBeatriz/cenas/Nave2.gd
  microjogos/2023S1/projetoAnaBeatriz/cenas/SpaceShip.gd
  microjogos/2023S1/projetoAnaBeatriz/cenas/StarfieldAlpha.gd
  microjogos/2023S1/projetoAnaBeatriz/cenas/StaticBody2D.gd
  microjogos/2023S1/projetoAnaBeatriz/cenas/Timer.gd
  microjogos/2023S1/projetoAnaBeatriz/cenas/Ufo2.gd
  microjogos/2023S1/projetoAnaBeatriz/cenas/cenas.txt
  microjogos/2023S1/projetoAnaBeatriz/cenas/inimigo.tscn
  microjogos/2023S1/projetoAnaBeatriz/cenas/inimigos_2.gd
  microjogos/2023S1/projetoAnaBeatriz/cenas/inimigos_2.tscn
  microjogos/2023S1/projetoAnaBeatriz/cenas/inimki.gd
  microjogos/2023S1/projetoAnaBeatriz/cenas/inimki.tscn
  microjogos/2023S1/projetoAnaBeatriz/cenas/main.gd
  microjogos/2023S1/projetoAnaBeatriz/cenas/main.tscn
  microjogos/2023S1/projetoAnaBeatriz/cenas/nave_1.gd
  microjogos/2023S1/projetoAnaBeatriz/cenas/nave_1.tscn
  microjogos/2023S1/projetoAnaBeatriz/cenas/player.gd
  microjogos/2023S1/projetoAnaBeatriz/cenas/player.tscn
  microjogos/2023S1/projetoAnaBeatriz/cenas/scripts/main.gd
  microjogos/2023S1/projetoAnaBeatriz/cenas/scripts/scripts.txt
  microjogos/2023S1/projetoAnaBeatriz/cenas/shot.gd
  microjogos/2023S1/projetoAnaBeatriz/cenas/shot.tscn
  microjogos/2023S1/projetoAnaBeatriz/cenas/space_ship.tscn
  microjogos/2023S1/projetoAnaBeatriz/creditos.gd
  microjogos/2023S1/projetoAnaBeatriz/recursos/Nave_1.png
  microjogos/2023S1/projetoAnaBeatriz/recursos/Nave_1.png.import
  microjogos/2023S1/projetoAnaBeatriz/recursos/SpaceShip.png
  microjogos/2023S1/projetoAnaBeatriz/recursos/SpaceShip.png.import
  microjogos/2023S1/projetoAnaBeatriz/recursos/UFO.png
  microjogos/2023S1/projetoAnaBeatriz/recursos/UFO.png.import
  microjogos/2023S1/projetoAnaBeatriz/recursos/Ufo2.png
  microjogos/2023S1/projetoAnaBeatriz/recursos/Ufo2.png.import
  microjogos/2023S1/projetoAnaBeatriz/recursos/inimigos2.png
  microjogos/2023S1/projetoAnaBeatriz/recursos/inimigos2.png.import
  microjogos/2023S1/projetoAnaBeatriz/recursos/inimki.png
  microjogos/2023S1/projetoAnaBeatriz/recursos/inimki.png.import
  microjogos/2023S1/projetoAnaBeatriz/recursos/nave2.png
  microjogos/2023S1/projetoAnaBeatriz/recursos/nave2.png.import
  microjogos/2023S1/projetoAnaBeatriz/recursos/recursos.txt
  microjogos/2023S1/projetoAnaBeatriz/recursos/shipI.png
  microjogos/2023S1/projetoAnaBeatriz/recursos/shipI.png.import
  microjogos/2023S1/projetoAnaBeatriz/recursos/starfield_alpha.png
  microjogos/2023S1/projetoAnaBeatriz/recursos/starfield_alpha.png.import
  microjogos/2023S1/projetoAnaBeatriz/seu projeto.txt
  microjogos/2023S1/seu_projeto/cenas/scripts/main.gd
Labels: Complete minigame, Missing sound, Missing icon, Incomplete credits, bug: bind main.gd

#89 Projeto esteche
  microjogos/2023S1/projeto-esteche/capa.png
  microjogos/2023S1/projeto-esteche/capa.png.import
  microjogos/2023S1/projeto-esteche/cenas/Asteroide.gd
  microjogos/2023S1/projeto-esteche/cenas/Astronauta.gd
  microjogos/2023S1/projeto-esteche/cenas/PlataformaDireita.gd
  microjogos/2023S1/projeto-esteche/cenas/area_2d.tscn
  microjogos/2023S1/projeto-esteche/cenas/areadepouso.gd
  microjogos/2023S1/projeto-esteche/cenas/main.tscn
  microjogos/2023S1/projeto-esteche/cenas/scripts/main.gd
  microjogos/2023S1/projeto-esteche/cenas/scripts/scripts.txt
  microjogos/2023S1/projeto-esteche/creditos.gd
  microjogos/2023S1/projeto-esteche/recursos/recursos.txt
  microjogos/2023S1/projeto-esteche/recursos/sounds/VictorySmall.ogg
  microjogos/2023S1/projeto-esteche/recursos/sounds/VictorySmall.ogg.import
  microjogos/2023S1/projeto-esteche/recursos/sounds/bg_music.ogg
  microjogos/2023S1/projeto-esteche/recursos/sounds/bg_music.ogg.import
  microjogos/2023S1/projeto-esteche/recursos/sounds/bg_music.wav.import
  microjogos/2023S1/projeto-esteche/recursos/sounds/explosion1.ogg
  microjogos/2023S1/projeto-esteche/recursos/sounds/explosion1.ogg.import
  microjogos/2023S1/projeto-esteche/recursos/sprites/Asteroid Brown.png
  microjogos/2023S1/projeto-esteche/recursos/sprites/Asteroid Brown.png.import
  microjogos/2023S1/projeto-esteche/recursos/sprites/Plataforma1.png
  microjogos/2023S1/projeto-esteche/recursos/sprites/Plataforma1.png.import
  microjogos/2023S1/projeto-esteche/recursos/sprites/bg.png
  microjogos/2023S1/projeto-esteche/recursos/sprites/bg.png.import
  microjogos/2023S1/projeto-esteche/recursos/sprites/cr_flying.png
  microjogos/2023S1/projeto-esteche/recursos/sprites/cr_flying.png.import
  microjogos/2023S1/projeto-esteche/recursos/sprites/cr_neutral.png
  microjogos/2023S1/projeto-esteche/recursos/sprites/cr_neutral.png.import
  microjogos/2023S1/projeto-esteche/recursos/sprites/plataforma.png
  microjogos/2023S1/projeto-esteche/recursos/sprites/plataforma.png.import
  microjogos/2023S1/projeto-esteche/seu projeto.txt
Labels: Complete minigame, Missing sound, Incomplete credits

#90 Minigame bugfixing
  microjogos/2023S1/GamutoVeiga/cenas/scripts/main.gd
  microjogos/2023S1/projeto-RafaelCarro/cenas/main.tscn
  microjogos/2023S1/projeto-RafaelCarro/cenas/scripts/Key.gd
  microjogos/2023S1/projeto-RafaelCarro/cenas/scripts/main.gd
  microjogos/2023S1/projeto-pochete/cenas/Head.gd
Labels: Bug, Enhancement

#95 Adds better visibility for checkboxes
  principal/cenas/Menu.tscn
  principal/recursos/themes/ButtonStyleBox.tres
  principal/recursos/themes/ButtonTheme.tres
Labels: Enhancement

#94 Reimplement soulchain
  microjogos/moraguma/soulchain/cenas/Hook.tscn
  microjogos/moraguma/soulchain/cenas/Main.tscn
  microjogos/moraguma/soulchain/cenas/Player.tscn
  microjogos/moraguma/soulchain/cenas/scripts/Main.gd
  microjogos/moraguma/soulchain/cenas/scripts/Player.gd
Labels: Minigame Implementation

#97 Unwanted notification system use removed
  microjogos/2023S1/projeto-brabesf/cenas/scripts/main.gd
Labels: Minigame Implementation

#98 Fixes out of range bug
  microjogos/2023S1/projeto-guglielmo-223300/cenas/scripts/Teclado.gd
Labels: Bug

#99 Fixes debugger errors
  microjogos/2023S1/projeto-yan-oliveira/cenas/main.tscn
  microjogos/2023S1/projeto-yan-oliveira/cenas/scripts/Mosca.gd
  microjogos/2023S1/projeto-yan-oliveira/cenas/scripts/Player.gd
  microjogos/2023S1/projeto-yan-oliveira/cenas/scripts/main.gd
Labels: Bug
