Repository moraguma/GamutoWare, pull requests merged in 2023-05, with the labels that each got.

#71 Fixes Frogger game display
  microjogos/demo/frogger/cenas/Car.tscn
  principal/cenas/scripts/Jogo.gd
Labels: Bug

#59 Implementação projeto pochete
  microjogos/2023S1/projeto-pochete/capa.png
  microjogos/2023S1/projeto-pochete/capa.png.import
  microjogos/2023S1/projeto-pochete/cenas/Apple.tscn
  microjogos/2023S1/projeto-pochete/cenas/Head.gd
  microjogos/2023S1/projeto-pochete/cenas/Tail.tscn
  microjogos/2023S1/projeto-pochete/cenas/cenas.txt
  microjogos/2023S1/projeto-pochete/cenas/main.tscn
  microjogos/2023S1/projeto-pochete/cenas/scripts/main.gd
  microjogos/2023S1/projeto-pochete/cenas/scripts/scripts.txt
  microjogos/2023S1/projeto-pochete/creditos.gd
  microjogos/2023S1/projeto-pochete/recursos/Forest_Ambience.mp3
  microjogos/2023S1/projeto-pochete/recursos/Forest_Ambience.mp3.import
  microjogos/2023S1/projeto-pochete/recursos/apple_bite_0.ogg
  microjogos/2023S1/projeto-pochete/recursos/apple_bite_0.ogg.import
  microjogos/2023S1/projeto-pochete/recursos/recursos.txt
  microjogos/2023S1/projeto-pochete/recursos/textures_240.png
  microjogos/2023S1/projeto-pochete/recursos/textures_240.png.import
  microjogos/2023S1/projeto-pochete/seu projeto.txt
Labels: Minigame Implementation

#60 Added leonardo_valente_project
  microjogos/2023S1/projeto_leonardo_valente/capa.png
  microjogos/2023S1/projeto_leonardo_valente/capa.png.import
  microjogos/2023S1/projeto_leonardo_valente/cenas/Creeper.gd
  microjogos/2023S1/projeto_leonardo_valente/cenas/CreeperSpawner.gd
  microjogos/2023S1/projeto_leonardo_valente/cenas/Delay.gd
  microjogos/2023S1/projeto_leonardo_valente/cenas/Personagem.gd
  microjogos/2023S1/projeto_leonardo_valente/cenas/Timer.gd
  microjogos/2023S1/projeto_leonardo_valente/cenas/TimerHide.gd
  microjogos/2023S1/projeto_leonardo_valente/cenas/TimerIgnite.gd
  microjogos/2023S1/projeto_leonardo_valente/cenas/TimerMatarPlayer.gd
  microjogos/2023S1/projeto_leonardo_valente/cenas/cenas.txt
  microjogos/2023S1/projeto_leonardo_valente/cenas/creeper.tscn
  microjogos/2023S1/projeto_leonardo_valente/cenas/main.gd
  microjogos/2023S1/projeto_leonardo_valente/cenas/main.tscn
  microjogos/2023S1/projeto_leonardo_valente/cenas/scripts/main.gd
  microjogos/2023S1/projeto_leonardo_valente/cenas/scripts/scripts.txt
  microjogos/2023S1/projeto_leonardo_valente/cenas/vinicinho.gd
  microjogos/2023S1/projeto_leonardo_valente/creditos.gd
  microjogos/2023S1/projeto_leonardo_valente/recursos/CovaVinicin.png
  microjogos/2023S1/projeto_leonardo_valente/recursos/CovaVinicin.png.import
  microjogos/2023S1/projeto_leonardo_valente/recursos/Spritesheet Creeper.png
  microjogos/2023S1/projeto_leonardo_valente/recursos/Spritesheet Creeper.png.import
  microjogos/2023S1/projeto_leonardo_valente/recursos/bad-explosion-6855.mp3
  microjogos/2023S1/projeto_leonardo_valente/recursos/bad-explosion-6855.mp3.import
  microjogos/2023S1/projeto_leonardo_valente/recursos/correvinicinho.wav
  microjogos/2023S1/projeto_leonardo_valente/recursos/correvinicinho.wav.import
  microjogos/2023S1/projeto_leonardo_valente/recursos/creeper1.png
  microjogos/2023S1/projeto_leonardo_valente/recursos/creeper1.png.import
  microjogos/2023S1/projeto_leonardo_valente/recursos/creeper2.png
  microjogos/2023S1/projeto_leonardo_valente/recursos/creeper2.png.import
  microjogos/2023S1/projeto_leonardo_valente/recursos/creeper3.png
  microjogos/2023S1/projeto_leonardo_valente/recursos/creeper3.png.import
  microjogos/2023S1/projeto_leonardo_valente/recursos/exp1.png
  microjogos/2023S1/projeto_leonardo_valente/recursos/exp1.png.import
  microjogos/2023S1/projeto_leonardo_valente/recursos/exp2.png
  microjogos/2023S1/projeto_leonardo_valente/recursos/exp2.png.import
  microjogos/2023S1/projeto_leonardo_valente/recursos/exp3.png
  microjogos/2023S1/projeto_leonardo_valente/recursos/exp3.png.import
  microjogos/2023S1/projeto_leonardo_valente/recursos/fundo.png
  microjogos/2023S1/projeto_leonardo_valente/recursos/fundo.png.import
  microjogos/2023S1/projeto_leonardo_valente/recursos/fundo160.png
  microjogos/2023S1/projeto_leonardo_valente/recursos/fundo160.png.import
  microjogos/2023S1/projeto_leonardo_valente/recursos/fundo2.png
  microjogos/2023S1/projeto_leonardo_valente/recursos/fundo2.png.import
  microjogos/2023S1/projeto_leonardo_valente/recursos/fundotentativa2.png
  microjogos/2023S1/projeto_leonardo_valente/recursos/fundotentativa2.png.import
  microjogos/2023S1/projeto_leonardo_valente/recursos/grama.jpg
  microjogos/2023S1/projeto_leonardo_valente/recursos/grama.jpg.import
  microjogos/2023S1/projeto_leonardo_valente/recursos/recursos.txt
  microjogos/2023S1/projeto_leonardo_valente/recursos/vinicinho.png
  microjogos/2023S1/projeto_leonardo_valente/recursos/vinicinho.png.import
  microjogos/2023S1/projeto_leonardo_valente/seu projeto.txt
Labels: Minigame Implementation

#62 Added projeto-thedeas
  microjogos/2023S1/projeto-thedeas/capa.png
  microjogos/2023S1/projeto-thedeas/capa.png.import
  microjogos/2023S1/projeto-thedeas/cenas/cenas.txt
  microjogos/2023S1/projeto-thedeas/cenas/main.gd
  microjogos/2023S1/projeto-thedeas/cenas/main.tscn
  microjogos/2023S1/projeto-thedeas/cenas/scripts/handMovment.gd
  microjogos/2023S1/projeto-thedeas/cenas/scripts/scripts.txt
  microjogos/2023S1/projeto-thedeas/creditos.gd
  microjogos/2023S1/projeto-thedeas/recursos/BackGround.png
  microjogos/2023S1/projeto-thedeas/recursos/BackGround.png.import
  microjogos/2023S1/projeto-thedeas/recursos/DeathGod.png
  microjogos/2023S1/projeto-thedeas/recursos/DeathGod.png.import
  microjogos/2023S1/projeto-thedeas/recursos/DeathGodSolo.png
  microjogos/2023S1/projeto-thedeas/recursos/DeathGodSolo.png.import
  microjogos/2023S1/projeto-thedeas/recursos/Folha.png
  microjogos/2023S1/projeto-thedeas/recursos/Folha.png.import
  microjogos/2023S1/projeto-thedeas/recursos/GodAnimation/DeathGod00.png
  microjogos/2023S1/projeto-thedeas/recursos/GodAnimation/DeathGod00.png.import
  microjogos/2023S1/projeto-thedeas/recursos/GodAnimation/DeathGod01.png
  microjogos/2023S1/projeto-thedeas/recursos/GodAnimation/DeathGod01.png.import
  microjogos/2023S1/projeto-thedeas/recursos/GodAnimation/DeathGod02.png
  microjogos/2023S1/projeto-thedeas/recursos/GodAnimation/DeathGod02.png.import
  microjogos/2023S1/projeto-thedeas/recursos/GodAnimation/DeathGod03.png
  microjogos/2023S1/projeto-thedeas/recursos/GodAnimation/DeathGod03.png.import
  microjogos/2023S1/projeto-thedeas/recursos/Mao.png
  microjogos/2023S1/projeto-thedeas/recursos/Mao.png.import
  microjogos/2023S1/projeto-thedeas/recursos/MaoSangue.png
  microjogos/2023S1/projeto-thedeas/recursos/MaoSangue.png.import
  microjogos/2023S1/projeto-thedeas/recursos/Monge.png
  microjogos/2023S1/projeto-thedeas/recursos/Monge.png.import
  microjogos/2023S1/projeto-thedeas/recursos/People.tscn
  microjogos/2023S1/projeto-thedeas/recursos/PreFabs/monge.tscn
  microjogos/2023S1/projeto-thedeas/recursos/SmashSound.wav
  microjogos/2023S1/projeto-thedeas/recursos/SmashSound.wav.import
  microjogos/2023S1/projeto-thedeas/recursos/TerrorSound.wav
  microjogos/2023S1/projeto-thedeas/recursos/TerrorSound.wav.import
  microjogos/2023S1/projeto-thedeas/recursos/recursos.txt
  microjogos/2023S1/projeto-thedeas/seu projeto.txt
Labels: Minigame Implementation

#63 Projeto yan oliveira
  microjogos/2023S1/projeto-yan-oliveira/capa.png
  microjogos/2023S1/projeto-yan-oliveira/capa.png.import
  microjogos/2023S1/projeto-yan-oliveira/cenas/cenas.txt
  microjogos/2023S1/projeto-yan-oliveira/cenas/main.tscn
  microjogos/2023S1/projeto-yan-oliveira/cenas/scripts/Linguada.gd
  microjogos/2023S1/projeto-yan-oliveira/cenas/scripts/Mosca.gd
  microjogos/2023S1/projeto-yan-oliveira/cenas/scripts/Player.gd
  microjogos/2023S1/projeto-yan-oliveira/cenas/scripts/RayCast2D.gd
  microjogos/2023S1/projeto-yan-oliveira/cenas/scripts/Sapo.gd
  microjogos/2023S1/projeto-yan-oliveira/cenas/scripts/linguada.gd
  microjogos/2023S1/projeto-yan-oliveira/cenas/scripts/main.gd
  microjogos/2023S1/projeto-yan-oliveira/cenas/scripts/sapo_mov.gd
  microjogos/2023S1/projeto-yan-oliveira/cenas/scripts/scripts.txt
  microjogos/2023S1/projeto-yan-oliveira/creditos.gd
  microjogos/2023S1/projeto-yan-oliveira/recursos/Beep.wav
  microjogos/2023S1/projeto-yan-oliveira/recursos/Beep.wav.import
  microjogos/2023S1/projeto-yan-oliveira/recursos/BeepBox-Song.ogg
  microjogos/2023S1/projeto-yan-oliveira/recursos/BeepBox-Song.ogg.import
  microjogos/2023S1/projeto-yan-oliveira/recursos/Design sem nome.png.import
  microjogos/2023S1/projeto-yan-oliveira/recursos/Lagoa Oficial.png
  microjogos/2023S1/projeto-yan-oliveira/recursos/Lagoa Oficial.png.import
  microjogos/2023S1/projeto-yan-oliveira/recursos/Lagoa.png
  microjogos/2023S1/projeto-yan-oliveira/recursos/Lagoa.png.import
  microjogos/2023S1/projeto-yan-oliveira/recursos/Mosca Bombada.png
  microjogos/2023S1/projeto-yan-oliveira/recursos/Mosca Bombada.png.import
  microjogos/2023S1/projeto-yan-oliveira/recursos/Sapo.png
  microjogos/2023S1/projeto-yan-oliveira/recursos/Sapo.png.import
  microjogos/2023S1/projeto-yan-oliveira/recursos/Xaropinho.png
  microjogos/2023S1/projeto-yan-oliveira/recursos/Xaropinho.png.import
  microjogos/2023S1/projeto-yan-oliveira/recursos/mosca nova.png
  microjogos/2023S1/projeto-yan-oliveira/recursos/mosca nova.png.import
  microjogos/2023S1/projeto-yan-oliveira/recursos/recursos.txt
  microjogos/2023S1/projeto-yan-oliveira/seu projeto.txt
Labels: Minigame Implementation

#66 Projeto glassmuto
  microjogos/2023S1/GamutoVeiga/capa.png
  microjogos/2023S1/GamutoVeiga/capa.png.import
  microjogos/2023S1/GamutoVeiga/cenas/Copo 2.gd
  microjogos/2023S1/GamutoVeiga/cenas/cenas.txt
  microjogos/2023S1/GamutoVeiga/cenas/main.tscn
  microjogos/2023S1/GamutoVeiga/cenas/scripts/Copo 1.gd
  microjogos/2023S1/GamutoVeiga/cenas/scripts/Copo 2.gd
  microjogos/2023S1/GamutoVeiga/cenas/scripts/Copo 3.gd
  microjogos/2023S1/GamutoVeiga/cenas/scripts/Copo2.gd
  microjogos/2023S1/GamutoVeiga/cenas/scripts/main.gd
  microjogos/2023S1/GamutoVeiga/cenas/scripts/node_2d.gd
  microjogos/2023S1/GamutoVeiga/cenas/scripts/scripts.txt
  microjogos/2023S1/GamutoVeiga/creditos.gd
  microjogos/2023S1/GamutoVeiga/recursos/3045034132_1.webp.import
  microjogos/2023S1/GamutoVeiga/recursos/94c9ea25ba53d22187b83be2e6cad233.webp.import
  microjogos/2023S1/GamutoVeiga/recursos/CRmABX.png.import
  microjogos/2023S1/GamutoVeiga/recursos/Copo.png
  microjogos/2023S1/GamutoVeiga/recursos/Copo.png.import
  microjogos/2023S1/GamutoVeiga/recursos/Efeito_1.ogg
  microjogos/2023S1/GamutoVeiga/recursos/Efeito_1.ogg.import
  microjogos/2023S1/GamutoVeiga/recursos/Efeito_Ganhou.ogg
  microjogos/2023S1/GamutoVeiga/recursos/Efeito_Ganhou.ogg.import
  microjogos/2023S1/GamutoVeiga/recursos/Efeito_Perdeu.ogg
  microjogos/2023S1/GamutoVeiga/recursos/Efeito_Perdeu.ogg.import
  microjogos/2023S1/GamutoVeiga/recursos/Fundo.png
  microjogos/2023S1/GamutoVeiga/recursos/Fundo.png.import
  microjogos/2023S1/GamutoVeiga/recursos/Glassmuto_song.ogg
  microjogos/2023S1/GamutoVeiga/recursos/Glassmuto_song.ogg.import
  microjogos/2023S1/GamutoVeiga/recursos/Glassmuto_song_loop.ogg
  microjogos/2023S1/GamutoVeiga/recursos/Glassmuto_song_loop.ogg.import
  microjogos/2023S1/GamutoVeiga/recursos/gamuto.png
  microjogos/2023S1/GamutoVeiga/recursos/gamuto.png.import
  microjogos/2023S1/GamutoVeiga/recursos/recursos.txt
  microjogos/2023S1/GamutoVeiga/recursos/seta.png
  microjogos/2023S1/GamutoVeiga/recursos/seta.png.import
  microjogos/2023S1/GamutoVeiga/seu projeto.txt
Labels: Minigame Implementation

#67 Projeto jose victor
  microjogos/2023S1/projeto-jose-victor/capa.png
  microjogos/2023S1/projeto-jose-victor/capa.png.import
  microjogos/2023S1/projeto-jose-victor/cenas/cenas.txt
  microjogos/2023S1/projeto-jose-victor/cenas/main.tscn
  microjogos/2023S1/projeto-jose-victor/cenas/player.tscn
  microjogos/2023S1/projeto-jose-victor/cenas/scripts/Miojin.gd
  microjogos/2023S1/projeto-jose-victor/cenas/scripts/main.gd
  microjogos/2023S1/projeto-jose-victor/cenas/scripts/player.gd
  microjogos/2023S1/projeto-jose-victor/cenas/scripts/scripts.txt
  microjogos/2023S1/projeto-jose-victor/creditos.gd
  microjogos/2023S1/projeto-jose-victor/recursos/218064__meaxx__apple-2.wav
  microjogos/2023S1/projeto-jose-victor/recursos/218064__meaxx__apple-2.wav.import
  microjogos/2023S1/projeto-jose-victor/recursos/Snake.png
  microjogos/2023S1/projeto-jose-victor/recursos/Snake.png.import
  microjogos/2023S1/projeto-jose-victor/seu projeto.txt
Labels: Minigame Implementation

#72 Added Bis Limão Project
  microjogos/2023S1/bis-limao/capa.png
  microjogos/2023S1/bis-limao/capa.png.import
  microjogos/2023S1/bis-limao/cenas/bis_limao.tscn
  microjogos/2023S1/bis-limao/cenas/bis_normal.tscn
  microjogos/2023S1/bis-limao/cenas/cenas.txt
  microjogos/2023S1/bis-limao/cenas/main.tscn
  microjogos/2023S1/bis-limao/cenas/scripts/bis move.gd
  microjogos/2023S1/bis-limao/cenas/scripts/gamuto.gd
  microjogos/2023S1/bis-limao/cenas/scripts/main.gd
  microjogos/2023S1/bis-limao/cenas/scripts/scripts.txt
  microjogos/2023S1/bis-limao/creditos.gd
  microjogos/2023S1/bis-limao/recursos/background antigo.jpg
  microjogos/2023S1/bis-limao/recursos/background antigo.jpg.import
  microjogos/2023S1/bis-limao/recursos/background novo.png
  microjogos/2023S1/bis-limao/recursos/background novo.png.import
  microjogos/2023S1/bis-limao/recursos/bis limao song.ogg
  microjogos/2023S1/bis-limao/recursos/bis limao song.ogg.import
  microjogos/2023S1/bis-limao/recursos/bis limao.png
  microjogos/2023S1/bis-limao/recursos/bis limao.png.import
  microjogos/2023S1/bis-limao/recursos/bis normal.png
  microjogos/2023S1/bis-limao/recursos/bis normal.png.import
  microjogos/2023S1/bis-limao/recursos/blue_eaten_anim.res
  microjogos/2023S1/bis-limao/recursos/bus azul.png
  microjogos/2023S1/bis-limao/recursos/bus azul.png.import
  microjogos/2023S1/bis-limao/recursos/bus limão.png
  microjogos/2023S1/bis-limao/recursos/bus limão.png.import
  microjogos/2023S1/bis-limao/recursos/bye_lemon_anim.res
  microjogos/2023S1/bis-limao/recursos/gamuto boca aberta.png
  microjogos/2023S1/bis-limao/recursos/gamuto boca aberta.png.import
  microjogos/2023S1/bis-limao/recursos/gamuto.png
  microjogos/2023S1/bis-limao/recursos/gamuto.png.import
  microjogos/2023S1/bis-limao/recursos/recursos.txt
  microjogos/2023S1/bis-limao/recursos/seta.png
  microjogos/2023S1/bis-limao/recursos/seta.png.import
  microjogos/2023S1/bis-limao/recursos/spacebar.png
  microjogos/2023S1/bis-limao/recursos/spacebar.png.import
  microjogos/2023S1/bis-limao/seu projeto.txt
Labels: Minigame Implementation

#73 Otaku no nipo
  microjogos/2023S1/bis-limao/capa.png
  microjogos/2023S1/bis-limao/cenas/scripts/bis move.gd
  microjogos/2023S1/bis-limao/cenas/scripts/gamuto.gd
  microjogos/2023S1/projeto-brabesf/cenas/scripts/main.gd
  microjogos/2023S1/projeto-jose-victor/cenas/main.tscn
  microjogos/2023S1/projeto-jose-victor/cenas/scripts/main.gd
  microjogos/2023S1/projeto-thedeas/cenas/main.gd
  microjogos/2023S1/projeto-thedeas/cenas/scripts/handMovment.gd
  microjogos/2023S1/projeto-yan-oliveira/cenas/scripts/linguada.gd
  microjogos/2023S1/projeto_vinicius_carvalho/cenas/Player.tscn
  microjogos/2023S1/projeto_vinicius_carvalho/cenas/mapa.tscn
  microjogos/2023S1/projeto_vinicius_carvalho/cenas/scripts/mapa.gd
  principal/cenas/scripts/Jogo.gd
  principal/recursos/data/Minigames.gd
Labels: Minigame Implementation

#3 Added Dreamwave Drums (RafaelCarro)
  microjogos/2023S1/projeto-RafaelCarro/capa.png
  microjogos/2023S1/projeto-RafaelCarro/capa.png.import
  microjogos/2023S1/projeto-RafaelCarro/cenas/cenas.txt
  microjogos/2023S1/projeto-RafaelCarro/cenas/main.tscn
  microjogos/2023S1/projeto-RafaelCarro/cenas/scripts/DownArrow.gd
  microjogos/2023S1/projeto-RafaelCarro/cenas/scripts/Drums.gd
  microjogos/2023S1/projeto-RafaelCarro/cenas/scripts/LeftArrow.gd
  microjogos/2023S1/projeto-RafaelCarro/cenas/scripts/RightArrow.gd
  microjogos/2023S1/projeto-RafaelCarro/cenas/scripts/SpaceKey.gd
  microjogos/2023S1/projeto-RafaelCarro/cenas/scripts/UpArrow.gd
  microjogos/2023S1/projeto-RafaelCarro/cenas/scripts/main.gd
  microjogos/2023S1/projeto-RafaelCarro/cenas/scripts/scripts.txt
  microjogos/2023S1/projeto-RafaelCarro/creditos.gd
  microjogos/2023S1/projeto-RafaelCarro/recursos/Background.jpg
  microjogos/2023S1/projeto-RafaelCarro/recursos/Background.jpg.import
  microjogos/2023S1/projeto-RafaelCarro/recursos/BeepBox-Song.wav
  microjogos/2023S1/projeto-RafaelCarro/recursos/BeepBox-Song.wav.import
  microjogos/2023S1/projeto-RafaelCarro/recursos/DownArrow.png
  microjogos/2023S1/projeto-RafaelCarro/recursos/DownArrow.png.import
  microjogos/2023S1/projeto-RafaelCarro/recursos/DownArrowHit.png
  microjogos/2023S1/projeto-RafaelCarro/recursos/DownArrowHit.png.import
  microjogos/2023S1/projeto-RafaelCarro/recursos/Error.wav
  microjogos/2023S1/projeto-RafaelCarro/recursos/Error.wav.import
  microjogos/2023S1/projeto-RafaelCarro/recursos/Hit1.wav
  microjogos/2023S1/projeto-RafaelCarro/recursos/Hit1.wav.import
  microjogos/2023S1/projeto-RafaelCarro/recursos/Hit2.wav
  microjogos/2023S1/projeto-RafaelCarro/recursos/Hit2.wav.import
  microjogos/2023S1/projeto-RafaelCarro/recursos/Hit3.wav
  microjogos/2023S1/projeto-RafaelCarro/recursos/Hit3.wav.import
  microjogos/2023S1/projeto-RafaelCarro/recursos/Hit4.wav
  microjogos/2023S1/projeto-RafaelCarro/recursos/Hit4.wav.import
  microjogos/2023S1/projeto-RafaelCarro/recursos/Hit5.wav
  microjogos/2023S1/projeto-RafaelCarro/recursos/Hit5.wav.import
  microjogos/2023S1/projeto-RafaelCarro/recursos/LeftArrow.png
  microjogos/2023S1/projeto-RafaelCarro/recursos/LeftArrow.png.import
  microjogos/2023S1/projeto-RafaelCarro/recursos/LeftArrow.png~
  microjogos/2023S1/projeto-RafaelCarro/recursos/LeftArrowHit.png
  microjogos/2023S1/projeto-RafaelCarro/recursos/LeftArrowHit.png.import
  microjogos/2023S1/projeto-RafaelCarro/recursos/Pixel Art DrumKit.png
  microjogos/2023S1/projeto-RafaelCarro/recursos/Pixel Art DrumKit.png.import
  microjogos/2023S1/projeto-RafaelCarro/recursos/RightArrow.png
  microjogos/2023S1/projeto-RafaelCarro/recursos/RightArrow.png.import
  microjogos/2023S1/projeto-RafaelCarro/recursos/RightArrowHit.png
  microjogos/2023S1/projeto-RafaelCarro/recursos/RightArrowHit.png.import
  microjogos/2023S1/projeto-RafaelCarro/recursos/SpaceKey.png
  microjogos/2023S1/projeto-RafaelCarro/recursos/SpaceKey.png.import
  microjogos/2023S1/projeto-RafaelCarro/recursos/SpaceKeyHit.png
  microjogos/2023S1/projeto-RafaelCarro/recursos/SpaceKeyHit.png.import
  microjogos/2023S1/projeto-RafaelCarro/recursos/UpArrow.png
  microjogos/2023S1/projeto-RafaelCarro/recursos/UpArrow.png.import
  microjogos/2023S1/projeto-RafaelCarro/recursos/UpArrowHit.png
  microjogos/2023S1/projeto-RafaelCarro/recursos/UpArrowHit.png.import
  microjogos/2023S1/projeto-RafaelCarro/recursos/recursos.txt
  microjogos/2023S1/projeto-RafaelCarro/seu projeto.txt
Labels: Complete minigame, Minigame Implementation

#74 Adds Carro minigame
  principal/recursos/data/Minigames.gd
Labels: Minigame Implementation

#79 Fixes keyboard bug
  microjogos/moraguma/ifuv/cenas/scripts/Main.gd
Labels: Bug
